import type { DiscoveryTarget } from "@/lib/types/instagram-imports";

export const MOCK_DISCOVERY_TARGETS: DiscoveryTarget[] = [
  {
    id: "disc_001",
    name: "BMW Clubs Germany",
    platform: "instagram",
    queryType: "topic",
    query: "BMW clubs Germany automotive community",
    country: "Germany",
    city: null,
    tags: ["bmw", "clubs", "germany"],
    status: "planned",
    notes: "Focus on public club pages and enthusiast groups.",
    createdAt: "2026-07-01T10:00:00.000Z",
  },
  {
    id: "disc_002",
    name: "Car Meets Frankfurt",
    platform: "instagram",
    queryType: "location",
    query: "car meets Frankfurt am Main",
    country: "Germany",
    city: "Frankfurt",
    tags: ["car-meets", "frankfurt", "events"],
    status: "researching",
    notes: "Collect public event organizer profiles only.",
    createdAt: "2026-07-02T08:30:00.000Z",
  },
  {
    id: "disc_003",
    name: "#bmwclub",
    platform: "instagram",
    queryType: "hashtag",
    query: "#bmwclub",
    country: null,
    city: null,
    tags: ["bmw", "hashtag"],
    status: "planned",
    notes: "Hashtag research for future public profile discovery.",
    createdAt: "2026-07-02T11:15:00.000Z",
  },
  {
    id: "disc_004",
    name: "Tuning Shops Stuttgart",
    platform: "google_places",
    queryType: "business_category",
    query: "tuning shops Stuttgart",
    country: "Germany",
    city: "Stuttgart",
    tags: ["tuning", "shops", "stuttgart"],
    status: "ready",
    notes: "Prepare Google Places import pipeline for Q3.",
    createdAt: "2026-06-28T14:00:00.000Z",
  },
  {
    id: "disc_005",
    name: "Wrap Shops Hessen",
    platform: "google_places",
    queryType: "business_category",
    query: "wrap shops Hessen vinyl wrapping",
    country: "Germany",
    city: null,
    tags: ["wrap", "vinyl", "hessen"],
    status: "researching",
    notes: null,
    createdAt: "2026-06-29T09:45:00.000Z",
  },
  {
    id: "disc_006",
    name: "JDM Clubs Munich",
    platform: "instagram",
    queryType: "topic",
    query: "JDM clubs Munich Japanese car community",
    country: "Germany",
    city: "Munich",
    tags: ["jdm", "munich", "clubs"],
    status: "planned",
    notes: "Cross-reference with existing ShiftIt Munich records.",
    createdAt: "2026-07-03T16:20:00.000Z",
  },
  {
    id: "disc_007",
    name: "Porsche Meetups Europe",
    platform: "website",
    queryType: "keyword",
    query: "Porsche meetups Europe public events calendar",
    country: null,
    city: null,
    tags: ["porsche", "europe", "events"],
    status: "planned",
    notes: "Identify public event listing websites.",
    createdAt: "2026-07-04T07:00:00.000Z",
  },
  {
    id: "disc_008",
    name: "Mercedes-Benz Clubs Austria",
    platform: "instagram",
    queryType: "topic",
    query: "Mercedes-Benz clubs Austria",
    country: "Austria",
    city: null,
    tags: ["mercedes", "austria", "clubs"],
    status: "archived",
    notes: "Merged into broader DACH Mercedes research.",
    createdAt: "2026-06-15T12:00:00.000Z",
  },
  {
    id: "disc_009",
    name: "Car Detailing Berlin",
    platform: "google_places",
    queryType: "business_category",
    query: "car detailing Berlin",
    country: "Germany",
    city: "Berlin",
    tags: ["detailing", "berlin"],
    status: "ready",
    notes: null,
    createdAt: "2026-07-04T13:30:00.000Z",
  },
  {
    id: "disc_010",
    name: "Euro Car Culture TikTok",
    platform: "tiktok",
    queryType: "topic",
    query: "European car culture creators",
    country: null,
    city: null,
    tags: ["tiktok", "creators", "europe"],
    status: "planned",
    notes: "Future platform expansion — public profiles only.",
    createdAt: "2026-07-05T09:00:00.000Z",
  },
  {
    id: "disc_011",
    name: "Track Day Channels",
    platform: "youtube",
    queryType: "keyword",
    query: "Nürburgring track day channels public",
    country: "Germany",
    city: null,
    tags: ["youtube", "track-day", "nurburgring"],
    status: "researching",
    notes: "Public channel metadata only.",
    createdAt: "2026-07-05T10:30:00.000Z",
  },
  {
    id: "disc_012",
    name: "VW Scene Netherlands",
    platform: "instagram",
    queryType: "location",
    query: "VW scene Netherlands car clubs",
    country: "Netherlands",
    city: null,
    tags: ["vw", "netherlands", "scene"],
    status: "planned",
    notes: "Amsterdam and Rotterdam focus areas.",
    createdAt: "2026-07-05T11:00:00.000Z",
  },
];
